/**
 * UNIVERSIDAD DE CUNDINAMARCA
 * Profesor Jorge Páramo Fonseca
 * HCRadiologia
 * @author Glo System
 * 
 */
package Formulario;
 
import HCRadiologia.TiposDatosContactos;
import java.awt.Color;
import javax.swing.JOptionPane;

 

public class FormTiposDatosContactos extends javax.swing.JFrame {

    TiposDatosContactos mitipD = new TiposDatosContactos();
    TiposDatosContactos[] miLista =mitipD.crudListaTipoDato();
    boolean b;
    
    public FormTiposDatosContactos() {
        initComponents();
        this.setLocation(300,120);
        setSize(380,310);
        setResizable(false);
        this.getContentPane().setBackground(new Color (47,79,79));
        b=true;           
        for(int intCont = 0; intCont < miLista.length; intCont++){
        jComboD.addItem(miLista[intCont].getintIdTipoDato()+ "-"+miLista[intCont].getStrTipoDato());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboD = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Historia Clinica de Radiologia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 23, 310, 32);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 49, 20);

        jComboD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDActionPerformed(evt);
            }
        });
        getContentPane().add(jComboD);
        jComboD.setBounds(130, 80, 120, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iniciales");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 60, 20);

        txtDato.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtDato);
        txtDato.setBounds(130, 120, 120, 30);

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(30, 200, 70, 23);

        btnInsert.setText("Insertar");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(110, 200, 80, 23);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(200, 200, 90, 23);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(290, 200, 80, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDActionPerformed
        if(b){
            mitipD = miLista[jComboD.getSelectedIndex()];

            txtDato.setText(mitipD.getStrTipoDato());
            

            TiposDatosContactos mD = new TiposDatosContactos();
            TiposDatosContactos[] lD = mD.crudListaTipoDato();
            mD=lD[jComboD.getSelectedIndex()];
            int varId=mD.getintIdTipoDato();
            String varInD=mD.getStrTipoDato();
            

            txtDato.setText(varInD);
            btnInsert.setEnabled(false);
        }
    }//GEN-LAST:event_jComboDActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        b=false;

        txtDato.setText("");
        jComboD.removeAllItems();
        btnInsert.setEnabled(true);
        jComboD.repaint();

        for(int intCont = 0; intCont < miLista.length; intCont++){
            jComboD.addItem(miLista[intCont].getintIdTipoDato()+ "-"+miLista[intCont].getStrTipoDato());
        }
        jComboD.setSelectedIndex(0);
        b=true;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        mitipD.crudCrearTipoDato(txtDato.getText());
        txtDato.setText("");
        
        JOptionPane.showMessageDialog(null, "Se creo el registro", "Crecion",2);//Mensaje de exito (dato 2)
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int t= jComboD.getSelectedIndex();
        t= mitipD.getintIdTipoDato();
        mitipD.crudActualizarTipoDato(t,txtDato.getText());
        txtDato.setText(mitipD.getStrTipoDato());
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiposDatosContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiposDatosContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiposDatosContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiposDatosContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiposDatosContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox jComboD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
