/**
 * UNIVERSIDAD DE CUNDINAMARCA
 * Profesor Jorge Páramo Fonseca
 * HCRadiologia
 * @author Glo System
 * 
 */
package Formulario;

import HCRadiologia.Eps;
import HCRadiologia.Persona;
import HCRadiologia.RH;
import HCRadiologia.TipoDocumento;
import java.awt.Color;
import javax.swing.JOptionPane;


public class FormPersona extends javax.swing.JFrame {
 TipoDocumento mitipDoc = new TipoDocumento();
 TipoDocumento[] miLista =mitipDoc.crudListaTipoDocumento();//array
 Persona miPer = new Persona();
 Persona[] miLista1 =miPer.crudListaPersona();//array
 RH miRH = new RH();
 RH[] miLista2 =miRH.crudListaRH();//array
 Eps miEps = new Eps();
 Eps[] miLista3 =miEps.crudListaEps();//array
 boolean b;
    /**
     * Creates new form FormPersona
     */
    public FormPersona() {
        initComponents();
        
       
        
        txtMedPer.setVisible(false);
        lblMedPer.setVisible(false);
        txtGenero.setVisible(false);
        lblGenero.setVisible(false);
        txtTipD.setVisible(false);
        txtEps.setVisible(false);
        txtSangre.setVisible(false);
        
        this.getContentPane().setBackground(new Color (47,79,79));
        setSize(670,430);
        setResizable(false);
        b=true;           
        for(int intCont = 0; intCont < miLista.length; intCont++){
        jComboTipDoc.addItem(miLista[intCont].getIntIdTipo()+ "-"+miLista[intCont].getStrCInicialesTipoDoc()+"-"+miLista[intCont].getstrTipDoc());
        }
        for(int intCont = 0; intCont < miLista1.length; intCont++){
        jComboId.addItem(miLista1[intCont].getIntCodPer()+ "-"+miLista1[intCont].getStrNumDoc()+"-"+miLista1[intCont].getStrPNom());
        }
        for(int intCont = 0; intCont < miLista2.length; intCont++){
        jComboTipoSangre.addItem(miLista2[intCont].getIntIdRh()+ "-"+miLista2[intCont].getStrNomRh());
        }
        for(int intCont = 0; intCont < miLista3.length; intCont++){
        jComboEps.addItem(miLista3[intCont].getIntIdEps()+ "-"+miLista3[intCont].getStrNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboId = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMedPer = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        txtPNom = new javax.swing.JTextField();
        txtPApe = new javax.swing.JTextField();
        txtSApe = new javax.swing.JTextField();
        txtMedPer = new javax.swing.JTextField();
        txtFNac = new javax.swing.JTextField();
        txtEps = new javax.swing.JTextField();
        txtObs = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        BtnClean = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnDatosContacto = new javax.swing.JButton();
        jComboGenero = new javax.swing.JComboBox();
        jComboTipDoc = new javax.swing.JComboBox();
        txtGenero = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtSNom = new javax.swing.JTextField();
        jComboTipoSangre = new javax.swing.JComboBox();
        jComboEps = new javax.swing.JComboBox();
        txtSangre = new javax.swing.JTextField();
        txtTipD = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        lblEsp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Historia Clinica de Radiologia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 17, 310, 32);

        jComboId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboIdActionPerformed(evt);
            }
        });
        getContentPane().add(jComboId);
        jComboId.setBounds(136, 67, 160, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(98, 70, 40, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de documento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(17, 104, 140, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de documento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(325, 66, 110, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Primer nombre");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 120, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Segundo nombre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(326, 98, 100, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Primer apellido");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 170, 120, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Segundo Apellido");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(326, 130, 100, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Genero");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 30, 50, 20);

        lblMedPer.setText("Medico");
        getContentPane().add(lblMedPer);
        lblMedPer.setBounds(521, 336, 33, 14);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de nacimiento");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 210, 130, 20);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tipo de sangre");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 244, 120, 20);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Eps");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(335, 165, 30, 20);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Observaciones");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(326, 199, 100, 20);

        txtNumDoc.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtNumDoc);
        txtNumDoc.setBounds(174, 101, 100, 20);

        txtPNom.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtPNom);
        txtPNom.setBounds(174, 133, 100, 20);

        txtPApe.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtPApe);
        txtPApe.setBounds(174, 171, 100, 20);

        txtSApe.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtSApe);
        txtSApe.setBounds(460, 133, 105, 20);
        getContentPane().add(txtMedPer);
        txtMedPer.setBounds(558, 333, 28, 20);

        txtFNac.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtFNac);
        txtFNac.setBounds(174, 209, 100, 20);
        getContentPane().add(txtEps);
        txtEps.setBounds(488, 333, 21, 20);

        txtObs.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtObs);
        txtObs.setBounds(442, 202, 105, 20);

        btnActualizar.setText("Actializar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(71, 292, 100, 23);

        btnInsert.setText("Insertar");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(190, 290, 80, 23);

        BtnClean.setText("Limpiar");
        BtnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCleanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClean);
        BtnClean.setBounds(290, 290, 90, 23);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(246, 333, 70, 23);

        btnDatosContacto.setText("Ingresar datos de contacto");
        btnDatosContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosContactoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatosContacto);
        btnDatosContacto.setBounds(390, 290, 190, 23);

        jComboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jComboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboGenero);
        jComboGenero.setBounds(460, 32, 104, 20);

        jComboTipDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipDocActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipDoc);
        jComboTipDoc.setBounds(460, 63, 105, 20);
        getContentPane().add(txtGenero);
        txtGenero.setBounds(558, 354, 28, 20);

        lblGenero.setText("Genero");
        getContentPane().add(lblGenero);
        lblGenero.setBounds(519, 357, 35, 14);

        txtSNom.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtSNom);
        txtSNom.setBounds(460, 95, 105, 20);

        jComboTipoSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoSangreActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipoSangre);
        jComboTipoSangre.setBounds(175, 244, 92, 20);

        jComboEps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEpsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboEps);
        jComboEps.setBounds(451, 171, 105, 20);
        getContentPane().add(txtSangre);
        txtSangre.setBounds(488, 354, 21, 20);
        getContentPane().add(txtTipD);
        txtTipD.setBounds(596, 354, 26, 20);

        txtEspecialidad.setMargin(new java.awt.Insets(-3, -3, -3, -3));
        getContentPane().add(txtEspecialidad);
        txtEspecialidad.setBounds(442, 240, 123, 20);

        lblEsp.setForeground(new java.awt.Color(255, 255, 255));
        lblEsp.setText("Especialidad");
        getContentPane().add(lblEsp);
        lblEsp.setBounds(323, 237, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosContactoActionPerformed
        
        FormDatosContactoPersona dato = new FormDatosContactoPersona();
        dato.txtIdper.setText(jComboId.getSelectedItem().toString());
        dato.txtPersona.setText(""+Integer.parseInt(""+(jComboId.getSelectedIndex()+1)));
        dato.txtPersona.setEditable(false);
        dato.txtPersona.setVisible(false);
        dato.setVisible(true);
        setVisible(false);
        
        
        dato.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnDatosContactoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jComboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGeneroActionPerformed
        if(jComboGenero.getSelectedItem().toString()=="Masculino")
    {
        txtGenero.setText("1");
        
    }else if(jComboGenero.getSelectedItem().toString()=="Femenino")
    {
        txtGenero.setText("0");
    }
    }//GEN-LAST:event_jComboGeneroActionPerformed

    private void jComboTipDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipDocActionPerformed
         if(b){
            mitipDoc = miLista[jComboTipDoc.getSelectedIndex()];
            txtTipD.setText(""+mitipDoc.getIntIdTipo());
        }
    }//GEN-LAST:event_jComboTipDocActionPerformed

    private void jComboIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboIdActionPerformed
        if(b){
        miPer = miLista1[jComboId.getSelectedIndex()];
        
        txtTipD.setText(""+miPer.getIntTipoDocumento());
        txtNumDoc.setText(miPer.getStrNumDoc());
        txtPNom.setText(miPer.getStrPNom());
        txtSNom.setText(miPer.getStrSNom());
        txtPApe.setText(miPer.getStrPApe());
        txtSApe.setText(miPer.getStrSApe());
        txtFNac.setText(miPer.getStrFecNac());
        txtSangre.setText(""+miPer.getIntRH());
        txtEps.setText(""+miPer.getIntEps());
        txtObs.setText(miPer.getStrObservacionesPersona());

        Persona mD = new Persona();
        Persona[] lD = mD.crudListaPersona();
        mD=lD[jComboId.getSelectedIndex()];
        int varId=mD.getIntCodPer();
        int varD = mD.getIntTipoDocumento();
        String varInD=mD.getStrNumDoc();
        String varP = mD.getStrPNom();
        String varS = mD.getStrSNom();
        String varA = mD.getStrPApe();
        String varAS = mD.getStrSApe();
        String varF = mD.getStrFecNac();
        int varR = mD.getIntRH();
        int varE = mD.getIntEps();
        String varO = mD.getStrObservacionesPersona();
        
        txtTipD.setText(""+varD);
        txtNumDoc.setText(varInD);
        txtPNom.setText(varP);
        txtSNom.setText(varS);
        txtPApe.setText(varA);
        txtSApe.setText(varAS);
        txtFNac.setText(varF);
        txtSangre.setText(""+varR);
        txtEps.setText(""+varE);
        txtObs.setText(varO);
        
        }
        
    }//GEN-LAST:event_jComboIdActionPerformed

    private void jComboTipoSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoSangreActionPerformed
        if(b){
            miRH = miLista2[jComboTipoSangre.getSelectedIndex()];
            txtSangre.setText(""+miRH.getIntIdRh());
        }
    }//GEN-LAST:event_jComboTipoSangreActionPerformed

    private void jComboEpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEpsActionPerformed
        if(b){
            miEps = miLista3[jComboEps.getSelectedIndex()];
            txtEps.setText(""+miEps.getIntIdEps());
        }
    }//GEN-LAST:event_jComboEpsActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int t= jComboId.getSelectedIndex();
        t= miPer.getIntCodPer();
        
        miPer.crudActualizarPersona(t, Integer.parseInt(txtTipD.getText()),txtNumDoc.getText(),txtPNom.getText(),txtSNom.getText(),txtPApe.getText(),txtSApe.getText(),Integer.parseInt(txtGenero.getText()),Integer.parseInt(txtMedPer.getText()),txtFNac.getText(),Integer.parseInt(txtSangre.getText()), Integer.parseInt(txtEps.getText()),txtObs.getText());
        txtTipD.setText(""+miPer.getIntTipoDocumento());
        txtNumDoc.setText(miPer.getStrNumDoc());
        txtPNom.setText(miPer.getStrPNom());
        txtSNom.setText(miPer.getStrSNom());
        txtPApe.setText(miPer.getStrPApe());
        txtSApe.setText(miPer.getStrSApe());
        txtMedPer.setText(""+miPer.getbyteMedicoPersona());
        txtGenero.setText(""+miPer.getByteGenero());
        txtFNac.setText(miPer.getStrFecNac());
        txtSangre.setText(""+miPer.getIntRH());
        txtEps.setText(""+miPer.getIntEps());
        txtObs.setText(miPer.getStrObservacionesPersona());
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        
        miPer.crudCrearPersona(Integer.parseInt(txtTipD.getText()),txtNumDoc.getText(),txtPNom.getText(),txtSNom.getText(),txtPApe.getText(),txtSApe.getText(),Integer.parseInt(txtGenero.getText()),Integer.parseInt(txtMedPer.getText()),txtFNac.getText(),Integer.parseInt(txtSangre.getText()), Integer.parseInt(txtEps.getText()),txtObs.getText());
        txtTipD.setText("");
        txtNumDoc.setText("");
        txtPNom.setText("");
        txtSNom.setText("");
        txtPApe.setText("");
        txtSApe.setText("");
        txtMedPer.setText("");
        txtGenero.setText("");
        txtFNac.setText("");
        txtSangre.setText("");
        txtEps.setText("");
        txtObs.setText("");
      
       JOptionPane.showMessageDialog(null, "Se creo el registro", "Crecion de color",2);//Mensaje de exito (dato 2)
       MenuPrincipal menu = new MenuPrincipal();
       menu.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void BtnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClean;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnDatosContacto;
    public javax.swing.JButton btnInsert;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox jComboEps;
    private javax.swing.JComboBox jComboGenero;
    private javax.swing.JComboBox jComboId;
    private javax.swing.JComboBox jComboTipDoc;
    private javax.swing.JComboBox jComboTipoSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblEsp;
    public javax.swing.JLabel lblGenero;
    public javax.swing.JLabel lblMedPer;
    private javax.swing.JTextField txtEps;
    public javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtFNac;
    public javax.swing.JTextField txtGenero;
    public javax.swing.JTextField txtMedPer;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtPApe;
    private javax.swing.JTextField txtPNom;
    private javax.swing.JTextField txtSApe;
    private javax.swing.JTextField txtSNom;
    private javax.swing.JTextField txtSangre;
    private javax.swing.JTextField txtTipD;
    // End of variables declaration//GEN-END:variables
}
