/**
 * UNIVERSIDAD DE CUNDINAMARCA
 * Profesor Jorge Páramo Fonseca
 * HCRadiologia
 * @author Glo System
 * 
 */
package Formulario;

import java.awt.Color;
import javax.swing.JButton;


public class MenuPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(new Color (47,79,79));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTiposSangre = new javax.swing.JButton();
        btnEps = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnTiposDoc = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnTipoImg = new javax.swing.JButton();
        btnTiposDatosContactos = new javax.swing.JButton();
        btnPer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTiposSangre.setText("Tipos de sangre");
        btnTiposSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiposSangreActionPerformed(evt);
            }
        });

        btnEps.setText("EPS");
        btnEps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEpsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Historia Clinica de Radiologia");

        btnTiposDoc.setText("Tipos de Documento");
        btnTiposDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiposDocActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnTipoImg.setText("Tipos de imagen");
        btnTipoImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoImgActionPerformed(evt);
            }
        });

        btnTiposDatosContactos.setText("Tipos de dato de contacto");
        btnTiposDatosContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiposDatosContactosActionPerformed(evt);
            }
        });

        btnPer.setText("Ingreso datos persona");
        btnPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTiposSangre)
                                    .addComponent(btnTiposDoc))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTipoImg)
                                    .addComponent(btnTiposDatosContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEps, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSalir))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEps)
                    .addComponent(btnPer))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTiposDatosContactos)
                    .addComponent(btnTiposDoc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoImg)
                    .addComponent(btnTiposSangre))
                .addGap(30, 30, 30)
                .addComponent(btnSalir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTiposSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiposSangreActionPerformed
        FormRh rh = new FormRh();
        rh.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTiposSangreActionPerformed

    private void btnTiposDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiposDocActionPerformed
        FormTipoDocumento tip = new FormTipoDocumento();
        tip.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTiposDocActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Perfiles perfiles = new Perfiles();
        perfiles.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEpsActionPerformed
        FormEps eps = new FormEps();
        eps.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnEpsActionPerformed

    private void btnTiposDatosContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiposDatosContactosActionPerformed
        FormTiposDatosContactos tPC = new FormTiposDatosContactos();
        tPC.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTiposDatosContactosActionPerformed

    private void btnPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerActionPerformed
        MedicoPersona MP = new MedicoPersona();
        MP.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnPerActionPerformed

    private void btnTipoImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoImgActionPerformed
       FormTipoImagen tI = new FormTipoImagen();
        tI.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnTipoImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEps;
    private javax.swing.JButton btnPer;
    private javax.swing.JButton btnSalir;
    public javax.swing.JButton btnTipoImg;
    public javax.swing.JButton btnTiposDatosContactos;
    public javax.swing.JButton btnTiposDoc;
    public javax.swing.JButton btnTiposSangre;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

